import { language } from "./localize";

const en = {
  integrationNotLoaded: "Maintenance Countdown is not loaded. Add it in Settings → Devices & services, then refresh this page.",
  changesSaved: "Task changes saved. You can close the card editor.",
  taskCreated: "Task created",
  saveFailed: "Could not save task",
  invalidIcon: "Enter an icon name such as bacteria or mdi:bacteria",
  iconHint: "You can also type a name such as bacteria",
  loadingIcons: "Loading the Home Assistant icon list…",
  deleteConfirm: (name: string) => `Delete “${name}”? Existing cards will remain and show that the task is missing.`,
  taskDeleted: "Task deleted",
  deleteFailed: "Could not delete task",
  testSent: (delivered: number, failed: number) => `Test sent: ${delivered}; failed: ${failed}`,
  testFailed: "Could not send test notification",
  loading: "Loading tasks…",
  retry: "Retry",
  task: "Task",
  taskMode: "Task source",
  selectedTask: "Selected task",
  createNewTask: "New task",
  existingTask: "Existing task",
  chooseTask: "Choose a task…",
  selectTaskFirst: "Choose an existing task to continue",
  missingTask: "The selected task no longer exists",
  name: "Name",
  namePlaceholder: "For example, Water filter",
  icon: "Icon",
  intervalDays: "Interval, days",
  lastCompleted: "Last completed",
  today: "Today",
  warningWindow: "Warning window, days",
  nextDueDate: "Next due date",
  appearance: "Appearance",
  styleAria: "Card style",
  verticalSize: "Card height",
  verticalSizeAria: "Card height",
  compactSize: "Compact",
  standardSize: "Standard",
  wideSize: "Wide",
  bar: "Bar",
  cardFill: "Card fill",
  reverseProgress: "Reverse progress direction",
  accentColor: "Accent color",
  themeColor: "Theme color",
  showSecondary: "Show secondary line",
  secondaryLine: "Secondary line",
  dueDate: "Due date",
  behavior: "Behavior",
  confirmCompletion: "Confirm completion",
  tap: "Tap",
  complete: "Complete",
  moreInfo: "More info",
  hold: "Hold",
  doubleTap: "Double tap",
  noAction: "No action",
  notifications: "Notifications",
  sendNotifications: "Send notifications",
  persistentNotification: "Create a persistent Home Assistant notification",
  notificationTargets: "Notification targets",
  notificationTargetsUnavailable: "Notification targets could not be loaded. Saved targets are preserved; reopen the editor to retry.",
  compatibilityTarget: (name: string, id: string) => `${name} — compatible action (${id})`,
  unavailable: " — unavailable",
  optionalTitle: "Optional title",
  onWarning: "On entering warning",
  onDue: "On due date",
  message: "Message",
  placeholders: "Placeholders",
  notification: "Notification",
  livePreview: "Live preview",
  previewAuto: "Actual dates",
  previewNormal: "Normal",
  previewWarning: "Warning",
  previewDue: "Due",
  previewOverdue: "Overdue",
  previewTaskName: "Water filter",
  sendTest: "Send test",
  deleteTask: "Delete task",
  saving: "Saving…",
  saveTask: "Save task",
  createTask: "Create task",
  taskSaveHint: "Task data is saved separately from the card settings.",
} as const;

export type EditorStrings = {
  [Key in keyof typeof en]: (typeof en)[Key] extends (...args: infer Args) => string
    ? (...args: Args) => string
    : string;
};

const ru: EditorStrings = {
  integrationNotLoaded: "Интеграция Maintenance Countdown не загружена. Добавьте её в Настройки → Устройства и службы и обновите страницу.",
  changesSaved: "Изменения задачи сохранены. Редактор карточки можно закрыть.",
  taskCreated: "Задача создана",
  saveFailed: "Не удалось сохранить задачу",
  invalidIcon: "Введите имя иконки, например bacteria или mdi:bacteria",
  iconHint: "Можно также ввести имя, например bacteria",
  loadingIcons: "Загрузка списка иконок Home Assistant…",
  deleteConfirm: (name: string) => `Удалить задачу «${name}»? Карточки сохранятся и покажут, что задача не найдена.`,
  taskDeleted: "Задача удалена",
  deleteFailed: "Не удалось удалить задачу",
  testSent: (delivered: number, failed: number) => `Тест отправлен: ${delivered}; ошибок: ${failed}`,
  testFailed: "Не удалось отправить тестовое уведомление",
  loading: "Загрузка задач…",
  retry: "Повторить",
  task: "Задача",
  taskMode: "Источник задачи",
  selectedTask: "Выбранная задача",
  createNewTask: "Новая задача",
  existingTask: "Существующая",
  chooseTask: "Выберите задачу…",
  selectTaskFirst: "Выберите существующую задачу, чтобы продолжить",
  missingTask: "Выбранная задача больше не существует",
  name: "Название",
  namePlaceholder: "Например, Заменить фильтр",
  icon: "Иконка",
  intervalDays: "Период, дней",
  lastCompleted: "Последнее выполнение",
  today: "Сегодня",
  warningWindow: "Warning-период, дней",
  nextDueDate: "Следующий срок",
  appearance: "Внешний вид",
  styleAria: "Стиль карточки",
  verticalSize: "Высота карточки",
  verticalSizeAria: "Высота карточки",
  compactSize: "Компактная",
  standardSize: "Стандартная",
  wideSize: "Широкая",
  bar: "Полоса",
  cardFill: "Заливка карточки",
  reverseProgress: "Обратное направление прогресса",
  accentColor: "Акцентный цвет",
  themeColor: "Цвет темы",
  showSecondary: "Показывать вторичную строку",
  secondaryLine: "Вторичная строка",
  dueDate: "Дата срока",
  behavior: "Поведение",
  confirmCompletion: "Подтверждать выполнение",
  tap: "Нажатие",
  complete: "Выполнить",
  moreInfo: "Подробнее",
  hold: "Удержание",
  doubleTap: "Двойное нажатие",
  noAction: "Нет действия",
  notifications: "Уведомления",
  sendNotifications: "Отправлять уведомления",
  persistentNotification: "Создавать постоянное уведомление Home Assistant",
  notificationTargets: "Цели уведомлений",
  notificationTargetsUnavailable: "Не удалось загрузить цели уведомлений. Сохранённые цели не изменены; откройте редактор заново, чтобы повторить.",
  compatibilityTarget: (name: string, id: string) => `${name} — совместимое действие (${id})`,
  unavailable: " — недоступна",
  optionalTitle: "Заголовок, необязательно",
  onWarning: "При входе в warning",
  onDue: "В день истечения срока",
  message: "Текст сообщения",
  placeholders: "Подстановки",
  notification: "Уведомление",
  previewTaskName: "Заменить фильтр",
  livePreview: "Живое превью",
  previewAuto: "По датам задачи",
  previewNormal: "Обычное",
  previewWarning: "Предупреждение",
  previewDue: "Срок сегодня",
  previewOverdue: "Просрочено",
  sendTest: "Отправить тест",
  deleteTask: "Удалить задачу",
  saving: "Сохранение…",
  saveTask: "Сохранить задачу",
  createTask: "Создать задачу",
  taskSaveHint: "Данные задачи сохраняются отдельно от настроек карточки.",
};

export function editorStrings(locale?: string): EditorStrings {
  return language(locale) === "ru" ? ru : en;
}
