import { language } from "./localize";

const en = {
  integrationNotLoaded: "Cyclic Maintenance Countdown is not loaded. Add it in Settings → Devices & services, then refresh this page.",
  changesSaved: "Changes saved",
  taskCreated: "Task created",
  saveFailed: "Could not save task",
  deleteConfirm: (name: string) => `Delete “${name}”? Existing cards will remain and show that the task is missing.`,
  taskDeleted: "Task deleted",
  deleteFailed: "Could not delete task",
  saveFirst: "Save the task first",
  testSent: (delivered: number, failed: number) => `Test sent: ${delivered}; failed: ${failed}`,
  testFailed: "Could not send test notification",
  loading: "Loading tasks…",
  retry: "Retry",
  task: "Task",
  selectedTask: "Selected task",
  createNewTask: "Create a new task",
  name: "Name",
  namePlaceholder: "For example, Water filter",
  icon: "Icon",
  intervalDays: "Interval, days",
  lastCompleted: "Last completed",
  today: "Today",
  warningWindow: "Warning window, days",
  nextDueDate: "Next due date",
  appearance: "Appearance",
  styleAria: "Card style",
  verticalSize: "Vertical card size",
  verticalSizeAria: "Vertical card size",
  standardSize: "Standard",
  wideSize: "Wide",
  bar: "Bar",
  cardFill: "Card fill",
  reverseProgress: "Reverse progress direction",
  accentColor: "Accent color",
  themeColor: "Theme color",
  showSecondary: "Show secondary line",
  secondaryLine: "Secondary line",
  dueDate: "Due date",
  behavior: "Behavior",
  confirmCompletion: "Confirm completion",
  tap: "Tap",
  complete: "Complete",
  moreInfo: "More info",
  hold: "Hold",
  doubleTap: "Double tap",
  noAction: "No action",
  notifications: "Notifications",
  sendNotifications: "Send notifications",
  persistentNotification: "Create a persistent Home Assistant notification",
  notificationTargets: "Notification targets",
  unavailable: " — unavailable",
  optionalTitle: "Optional title",
  onWarning: "On entering warning",
  onDue: "On due date",
  message: "Message",
  placeholders: "Placeholders",
  notification: "Notification",
  livePreview: "Live preview",
  previewAuto: "Actual dates",
  previewNormal: "Normal",
  previewWarning: "Warning",
  previewDue: "Due",
  previewOverdue: "Overdue",
  previewTaskName: "Water filter",
  sendTest: "Send test",
  deleteTask: "Delete task",
  saving: "Saving…",
  saveTask: "Save task",
  createTask: "Create task",
} as const;

export type EditorStrings = {
  [Key in keyof typeof en]: (typeof en)[Key] extends (...args: infer Args) => string
    ? (...args: Args) => string
    : string;
};

const ru: EditorStrings = {
  integrationNotLoaded: "Интеграция Cyclic Maintenance Countdown не загружена. Добавьте её в Настройки → Устройства и службы и обновите страницу.",
  changesSaved: "Изменения сохранены",
  taskCreated: "Задача создана",
  saveFailed: "Не удалось сохранить задачу",
  deleteConfirm: (name: string) => `Удалить задачу «${name}»? Карточки сохранятся и покажут, что задача не найдена.`,
  taskDeleted: "Задача удалена",
  deleteFailed: "Не удалось удалить задачу",
  saveFirst: "Сначала сохраните задачу",
  testSent: (delivered: number, failed: number) => `Тест отправлен: ${delivered}; ошибок: ${failed}`,
  testFailed: "Не удалось отправить тестовое уведомление",
  loading: "Загрузка задач…",
  retry: "Повторить",
  task: "Задача",
  selectedTask: "Выбранная задача",
  createNewTask: "Создать новую задачу",
  name: "Название",
  namePlaceholder: "Например, Заменить фильтр",
  icon: "Иконка",
  intervalDays: "Период, дней",
  lastCompleted: "Последнее выполнение",
  today: "Сегодня",
  warningWindow: "Warning-период, дней",
  nextDueDate: "Следующий срок",
  appearance: "Внешний вид",
  styleAria: "Стиль карточки",
  verticalSize: "Размер карточки по вертикали",
  verticalSizeAria: "Размер карточки по вертикали",
  standardSize: "Стандартный",
  wideSize: "Широкий",
  bar: "Полоса",
  cardFill: "Заливка карточки",
  reverseProgress: "Обратное направление прогресса",
  accentColor: "Акцентный цвет",
  themeColor: "Цвет темы",
  showSecondary: "Показывать вторичную строку",
  secondaryLine: "Вторичная строка",
  dueDate: "Дата срока",
  behavior: "Поведение",
  confirmCompletion: "Подтверждать выполнение",
  tap: "Нажатие",
  complete: "Выполнить",
  moreInfo: "Подробнее",
  hold: "Удержание",
  doubleTap: "Двойное нажатие",
  noAction: "Нет действия",
  notifications: "Уведомления",
  sendNotifications: "Отправлять уведомления",
  persistentNotification: "Создавать постоянное уведомление Home Assistant",
  notificationTargets: "Цели уведомлений",
  unavailable: " — недоступна",
  optionalTitle: "Заголовок, необязательно",
  onWarning: "При входе в warning",
  onDue: "В день истечения срока",
  message: "Текст сообщения",
  placeholders: "Подстановки",
  notification: "Уведомление",
  previewTaskName: "Заменить фильтр",
  livePreview: "Живое превью",
  previewAuto: "По датам задачи",
  previewNormal: "Обычное",
  previewWarning: "Предупреждение",
  previewDue: "Срок сегодня",
  previewOverdue: "Просрочено",
  sendTest: "Отправить тест",
  deleteTask: "Удалить задачу",
  saving: "Сохранение…",
  saveTask: "Сохранить задачу",
  createTask: "Создать задачу",
};

export function editorStrings(locale?: string): EditorStrings {
  return language(locale) === "ru" ? ru : en;
}
